service: authorize
provider:
  name: openwhisk
  ignore_certs: true

functions:
  authorize-github:
    handler: authorize.main
    bind:
      - service:
          name: cloudantnosqldb
          instance: Cloudant-vm
    events:
      - http: GET /authorize

plugins:
  - serverless-openwhisk
